package com.mwos.ebochs.core.vm.bochs;

import com.mwos.ebochs.core.vm.AbstractVM;
import com.mwos.ebochs.core.vm.IVMDebugable;

public class BaseBochsVM extends AbstractVM implements IVMDebugable{


	@Override
	public Process debug() throws Exception {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String getName() {
		// TODO Auto-generated method stub
		return null;
	}
	
	
	
	public static final String DefaultSetting=
			"# configuration file generated by Bochs\r\n" + 
			"plugin_ctrl: unmapped=1, biosdev=1, speaker=1, extfpuirq=1, parallel=1, serial=1, gameport=1\r\n" + 
			"config_interface: win32config\r\n" + 
			"display_library: win32\r\n" + 
			"memory: host=%.mem, guest=%.mem\r\n" + 
			"romimage: file=\"%.dir/BIOS-bochs-latest\", address=0x0, options=none\r\n" + 
			"vgaromimage: file=\"%.dir/VGABIOS-lgpl-latest\"\r\n" + 
			"boot: %.boot\r\n" + 
			"floppy_bootsig_check: disabled=0\r\n" + 
			"floppya: type=1_44, 1_44=\"%.floppya\", status=inserted, write_protected=0\r\n" + 
			"# no floppyb\r\n" + 
			"ata0: enabled=1, ioaddr1=0x1f0, ioaddr2=0x3f0, irq=14\r\n" + 
			"ata0-master: type=none\r\n" + 
			"ata0-slave: type=none\r\n" + 
			"ata1: enabled=1, ioaddr1=0x170, ioaddr2=0x370, irq=15\r\n" + 
			"ata1-master: type=none\r\n" + 
			"ata1-slave: type=none\r\n" + 
			"ata2: enabled=0\r\n" + 
			"ata3: enabled=0\r\n" + 
			"optromimage1: file=none\r\n" + 
			"optromimage2: file=none\r\n" + 
			"optromimage3: file=none\r\n" + 
			"optromimage4: file=none\r\n" + 
			"optramimage1: file=none\r\n" + 
			"optramimage2: file=none\r\n" + 
			"optramimage3: file=none\r\n" + 
			"optramimage4: file=none\r\n" + 
			"pci: enabled=1, chipset=i440fx\r\n" + 
			"vga: extension=vbe, update_freq=5, realtime=1\r\n" + 
			"cpu: count=1, ips=4000000, model=bx_generic, reset_on_triple_fault=1, cpuid_limit_winnt=0, ignore_bad_msrs=1, mwait_is_nop=0\r\n" + 
			"cpuid: level=6, stepping=3, model=3, family=6, vendor_string=\"GenuineIntel\", brand_string=\"              Intel(R) Pentium(R) 4 CPU        \"\r\n" + 
			"cpuid: mmx=1, apic=xapic, simd=sse2, sse4a=0, misaligned_sse=0, sep=1, movbe=0, adx=0\r\n" + 
			"cpuid: aes=0, sha=0, xsave=0, xsaveopt=0, x86_64=1, 1g_pages=0, pcid=0, fsgsbase=0\r\n" + 
			"cpuid: smep=0, smap=0, mwait=1, vmx=1\r\n" + 
			"print_timestamps: enabled=0\r\n" + 
			"port_e9_hack: enabled=0\r\n" + 
			"private_colormap: enabled=0\r\n" + 
			"clock: sync=both, time0=local, rtc_sync=0\r\n" + 
			"# no cmosimage\r\n" + 
			"# no loader\r\n" + 
			"log: -\r\n" + 
			"logprefix: %t%e%d\r\n" + 
			"debug: action=ignore\r\n" + 
			"info: action=report\r\n" + 
			"error: action=report\r\n" + 
			"panic: action=ask\r\n" + 
			"keyboard: type=mf, serial_delay=250, paste_delay=100000, user_shortcut=none\r\n" + 
			"mouse: type=ps2, enabled=0, toggle=ctrl+mbutton\r\n" + 
			"sound: waveoutdrv=win, waveout=none, waveindrv=win, wavein=none, midioutdrv=win, midiout=none\r\n" + 
			"speaker: enabled=1, mode=sound\r\n" + 
			"parport1: enabled=1, file=none\r\n" + 
			"parport2: enabled=0\r\n" + 
			"com1: enabled=1, mode=null\r\n" + 
			"com2: enabled=0\r\n" + 
			"com3: enabled=0\r\n" + 
			"com4: enabled=0\r\n" + 
			"";
}
